### ISSUE TITLE
string.concat

### ISSUE THREAD

**Issue by MaxGraey** [AssemblyScript/universal-strings#1]
`string.concat $e : [stringref, stringref] -> [stringref]`

Is there any reason not to implement this method?

**Comment by dcodeIO** [comment]
I guess we'll also need other very basic instructions like `concat`, yeah.

**Comment by MaxGraey** [comment]
btw concat is unicode-independent operation.

**Comment by dcodeIO** [comment]
Added a note that `string.concat` and others may also be desirable :)
